#!d:/bin/sh.exe

# Environment
OOTFILE="$1"

# Regular expressions for each model item.
#
#        model title: title-name
# "^TITLE .*"
#
#        object: abstr-or-concrete? posX posY class&object-name
# "^OBJ: [01] [0-9]+ [0-9]+ ?.*$"   
#
#        attribute: attribute-name
# "^ATTR ?.*$"
#
#        service: service-name
# "^SERV ?.*$"
#
#        gen-spec: ObjGen ObjSpec Cardinality-to-Spec Card-to-Gen
# "^CON2 g [0-9]+ [0-9]+ \"[^\"]*\" \"[^\"]\" "  
#
#        instance: ObjFrom ObjTo Cardinality-to-Knowee Card-to-Knower
# "^CON2 i [0-9]+ [0-9]+ \"[^\"]*\" \"[^\"]\" "  
#
#        message: ObjFrom ObjTo Cardinality-to-To Card-to-From
# "^CON2 m [0-9]+ [0-9]+ \"[^\"]*\" \"[^\"]\" " 
#
#        whole-part: ObjWhole ObjPart Card-to-part Card-to-whole
# "^CON2 w [0-9]+ [0-9]+ \"[^\"]*\" \"[^\"]\" "  
#
#        Quacker: Shows manual connection placement.
# "^CON3 [0-9]+ [0-9]+ [0-9]+"   
#
# Rules:
# 
# The model title is the first element in the data file.
# 
# For OBJ: declarations, abstr-or-concrete = 1 for abstract-classes,
#   0 for class&object concretions.
#
# Object number refer to the sequence that the OBJ: declaration has been
#   placed in the OOTher data file, not to an absolute serial number. The
#   sequencing starts at 0, not 1.
#
# Attribute declarations immediately follow the OBJ: declaration, if
#   the object has any attributes.
#
# Service declarations immediately follow the ATTR declaration, if
#   the object has any attributes, or the OBJ: declaration otherwise, 
#   but only if the object has services.
# 
# Structure and connection declarations follow after object, attribute, and
#   service declarations have been made.
# Grep out the object names alone
classes=`egrep "^OBJ: " $OOTFILE | cut -d " " -f 5`

# Show all classes
#
#echo $classes

# Cut out attributes for each class and show
# 
for class in $classes
do
   echo $class
   attribs=`sed "/^OBJ: $class/,/^OBJ: /p" $OOTFILE | egrep "^ATTR .*$" | cut -d " " -f2`
   echo $attribs
done
